name: Update Member in Team
description: Updates a GitHub user in a specified team in an organization with a given role using the GitHub API.
author: Lee Lott

inputs:
  member-name:
    description: 'The slugified username of the member to be updated (e.g., "john-doe")'
    required: true
  team-name:
    description: 'The slugified name of the team (e.g., "code-approvers")'
    required: true
  role:
    description: 'The role to assign to the member ("member" or "maintainer")'
    required: true
    default: 'member'
  token:
    description: 'GitHub token with organization admin permissions'
    required: true
  owner:
    description: 'The owner of the organization (user or organization)'
    required: true

outputs:
  result:
    description: 'Result of the add member operation ("success" or "failure")'
    value: ${{ steps.action.outputs.result }}
  error-message:
    description: 'Error message if the add member operation fails'
    value: ${{ steps.action.outputs.error-message }}

runs:
  using: composite
  steps:
    - name: Update Member in Team
      id: action
      run: |
        source ${{ github.action_path }}/action.sh
        update_member_in_team "${{ inputs.member-name }}" "${{ inputs.team-name }}" "${{ inputs.role }}" "${{ inputs.token }}" "${{ inputs.owner }}"
      shell: bash
